[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["Evžen Wybitul <wybitul.evzen@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
biopython = "^1.78"
Sphinx = "^4.0.1"
ipython = "^7.23.1"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
